# James Clarke
# 04/08/2019
# All exception classes that can be interrupted

namespace exception
{
	# Base exception class
	class Exception
	{
		func Exception(message)
		{
			this.message = message
		}
	}

	# Called when an iterator has reached the end
	class NullIterException extends Exception
	{
		func NullIterException
		{
			super.Exception("The iterator has reached the end")
		}
	}

	# Called when a key is not found in a dictionary
	class KeyNotFoundException extends Exception
	{
		func KeyNotFoundException(key)
		{
			super.Exception("The given key was not found: " + key)
		}
	}
	
	# Called when an array index is not found in a dictionary
	class IndexOutOfRangeException extends Exception
	{
		func IndexOutOfRangeException(index)
		{
			super.Exception("The index was out of range: " + index)
		}
	}

	# Called when the user tries to access an invalid identifier
	class CannotFindVariableException extends Exception
	{
		func CannotFindVariableException(name)
		{
			super.Exception("Variable cannot be found: " + name)
		}
	}
}